apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob-1
  labels:
    {{- include "autocompounder.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjobs.get_rewards.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-cronjob-container
            image: your-image
            envFrom:
              - configMapRef:
                  name: my-configmap
              - secretRef:
                  name: my-secret