{{- if .Values.appSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $value := .Values.appSecret.env }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}