cronjobs:
  bond:
    schedule: "*/5 * * * *"
  ccompound:
    schedule: "*/5 * * * *"
  get_rewards:
    schedule: "*/5 * * * *"

image:
  repository: ghcr.io/instrumentalfi/compoundr
  pullPolicy: IfNotPresent
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
